In [1]:
import pandas as pd

# ### Sample Submission

# Load the training data:

In [2]:
train_df = pd.read_csv('data/train.csv')
train_df.head()

,Title,Description,location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area,Price_USD,Amount_USD
0,3 BHK Ready to Occupy Flat for sale in Runwal ...,Carefully laid out in the prime location of Gh...,mumbai,806 sqft,Ready to Move,Upper Basement out of 15,Resale,Semi-Furnished,East,Main Road,Runwal Orchard Residency,2,3,1 Covered,Freehold,NaN,NaN,NaN,199.0 USD,271084.0
1,2 BHK Ready to Occupy Flat for sale in Shilale...,Up for immediate sale is a 2 BHK apartment in ...,ahmedabad,900 sqft,Ready to Move,1 out of 4,Resale,Unfurnished,NaN,Main Road,Shilalekh Apartments,2,2,NaN,Freehold,NaN,NaN,NaN,70.0 USD,63012.0
2,2 BHK Ready to Occupy Flat for sale Koramangala,This magnificent 2 BHK Flat is available for s...,bangalore,1000 sqft,Ready to Move,Ground out of 7,New Property,Unfurnished,West,Garden/Park,NaN,2,1,1 Covered,Freehold,NaN,NaN,NaN,127.0 USD,186747.0
3,4 BHK Ready to Occupy Flat for sale in Hiranan...,Have a look at this immaculate 4 BHK flat for ...,thane,1520 sqft,Ready to Move,14 out of 27,Resale,Unfurnished,East,Garden/Park,Hiranandani Meadows,4,1,2 Covered,Freehold,NaN,NaN,NaN,144.0 USD,289157.0
4,3 BHK Ready to Occupy Flat for sale Jagatpur,Have a look at this immaculate 3 BHK flat for ...,ahmedabad,NaN,Ready to Move,3 out of 9,Resale,Unfurnished,NaN,NaN,NaN,3,NaN,NaN,NaN,1773 sqft,NaN,NaN,50.0 USD,90361.0

In [3]:
test_df = pd.read_csv('data/test_inputs.csv')
test_df.head()

,Title,Description,location,Carpet Area,Status,Floor,Transaction,Furnishing,facing,overlooking,Society,Bathroom,Balcony,Car Parking,Ownership,Super Area,Dimensions,Plot Area,Price_USD
0,3 BHK Ready to Occupy Flat for sale in Bhartiy...,"Thanisandra Main Road, Bangalore has an appeal...",bangalore,1415 sqft,Ready to Move,32 out of 32,Resale,Semi-Furnished,East,NaN,NaN,3,3,NaN,NaN,NaN,NaN,NaN,157.0 USD
1,3 BHK Ready to Occupy Flat for sale in DS Max ...,This ready to move-in 3 BHK flat is available ...,bangalore,NaN,Ready to Move,5 out of 5,Resale,Semi-Furnished,NaN,NaN,NaN,4,NaN,NaN,NaN,3350 sqft,NaN,NaN,46.0 USD
2,2 BHK Ready to Occupy Flat for sale in Vijay E...,2 BHK flat available for sale in Thane in the ...,thane,800 sqft,Ready to Move,5 out of 14,Resale,Semi-Furnished,East,Garden/Park,Vijay Enclave,2,2,NaN,Co-operative Society,NaN,NaN,NaN,NaN
3,2 BHK Ready to Occupy Flat for sale in Charany...,Have a look at this immaculate 2 BHK flat for ...,bangalore,NaN,Ready to Move,1 out of 3,Resale,Semi-Furnished,NaN,NaN,NaN,2,NaN,NaN,NaN,1100 sqft,NaN,NaN,87.0 USD
4,2 BHK Ready to Occupy Flat for sale Kalyan East,"Kalyan East, Thane has an appealing 2 BHK flat...",thane,NaN,Ready to Move,3 out of 4,Resale,Semi-Furnished,NaN,NaN,NaN,4,NaN,NaN,NaN,1100 sqft,NaN,NaN,48.0 USD


##### We’ll begin by calculating the average price of all the houses. It’s not the most accurate method, but it gives us a baseline and helps you understand how the submissions work.

In [4]:

train_df['Amount_USD'].mean()

np.float64(135075.36967741934)


#### The **y_pred** using the average price will be:

In [5]:
baseline = train_df['Amount_USD'].mean()

In [6]:
baseline

np.float64(135075.36967741934)

# Number of rows in our **y_true** are 6519. So, our **y_pred** will be

In [7]:
y_pred = [baseline] * 6344

#### We have our `y_pred` ready. Now! Go ahead and try the checking if the activity passes.
# 
#### 👈👈👈 Click on `Check Activity` to see the result.

#### Your turn now — feel free to delete the earlier code before continuing.

# ---

##### Your code:


print(test_df.shape)
print(train_df.shape)

In [8]:
train_df.isnull().sum() / len(train_df) * 100

Title            0.000000
Description      2.270219
location         0.000000
Carpet Area     54.190972
Status           0.147144
Floor            3.704872
Transaction      0.047296
Furnishing       2.201902
facing          47.995165
overlooking     52.314888
Society         65.205739
Bathroom         0.168164
Balcony         37.574229
Car Parking     62.262862
Ownership       44.426927
Super Area      46.870566
Dimensions     100.000000
Plot Area      100.000000
Price_USD        4.908298
Amount_USD       0.000000
dtype: float64

In [9]:
test_df.isnull().sum()/ len(test_df) * 100

Title            0.000000
Description      2.522068
location         0.015763
Carpet Area     53.467844
Status           0.220681
Floor            3.830391
Transaction      0.063052
Furnishing       1.607818
facing          46.878941
overlooking     51.418663
Society         64.060530
Bathroom         0.252207
Balcony         37.767970
Car Parking     61.317781
Ownership       43.521438
Super Area      47.178436
Dimensions     100.000000
Plot Area      100.000000
Price_USD        4.602774
dtype: float64

In [10]:
print(test_df.describe())
train_df.describe()

       Dimensions  Plot Area
count         0.0        0.0
mean          NaN        NaN
std           NaN        NaN
min           NaN        NaN
25%           NaN        NaN
50%           NaN        NaN
75%           NaN        NaN
max           NaN        NaN

       Dimensions  Plot Area    Amount_USD
count         0.0        0.0  1.902900e+04
mean          NaN        NaN  1.350754e+05
std           NaN        NaN  1.539746e+05
min           NaN        NaN  2.410000e+03
25%           NaN        NaN  7.228900e+04
50%           NaN        NaN  9.638600e+04
75%           NaN        NaN  1.385540e+05
max           NaN        NaN  5.060241e+06

In [11]:

test_df.info()
print(train_df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6344 entries, 0 to 6343
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        6344 non-null   object
 1   Description  6184 non-null   object
 2   location     6343 non-null   object
 3   Carpet Area  2952 non-null   object
 4   Status       6330 non-null   object
 5   Floor        6101 non-null   object
 6   Transaction  6340 non-null   object
 7   Furnishing   6242 non-null   object
 8   facing       3370 non-null   object
 9   overlooking  3082 non-null   object
 10  Society      2280 non-null   object
 11  Bathroom     6328 non-null   object
 12  Balcony      3948 non-null   object
 13  Car Parking  2454 non-null   object
 14  Ownership    3583 non-null   object
 15  Super Area   3351 non-null   object
 16  Dimensions   0 non-null      float64
 17  Plot Area    0 non-null      float64
 18  Price_USD    6052 non-null   object
dtypes: float64(2), object(17)
memory usage: 941.8+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19029 entries, 0 to 19028
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Title        19029 non-null  object
 1   Description  18597 non-null  object
 2   location     19029 non-null  object
 3   Carpet Area  8717 non-null   object
 4   Status       19001 non-null  object
 5   Floor        18324 non-null  object
 6   Transaction  19020 non-null  object
 7   Furnishing   18610 non-null  object
 8   facing       9896 non-null   object
 9   overlooking  9074 non-null   object
 10  Society      6621 non-null   object
 11  Bathroom     18997 non-null  object
 12  Balcony      11879 non-null  object
 13  Car Parking  7181 non-null   object
 14  Ownership    10575 non-null  object
 15  Super Area   10110 non-null  object
 16  Dimensions   0 non-null      float64
 17  Plot Area    0 non-null      float64
 18  Price_USD    18095 non-null  object
 19  Amount_USD   19029 non-null  float64
dtypes: float64(3), object(17)
memory usage: 2.9+ MB
None

In [12]:

train_df['location'].unique()

array(['mumbai', 'ahmedabad', 'bangalore', 'thane', 'navi-mumbai',
       'nagpur'], dtype=object)

In [13]:

test_df['Carpet Area'].unique()

array(['1415 sqft', nan, '800 sqft', '900 sqft', '1036 sqft', '1350 sqft',
       '860 sqft', '2160 sqft', '880 sqft', '1000 sqft', '1050 sqft',
       '1250 sqft', '875 sqft', '275 sqyrd', '3500 sqft', '1125 sqft',
       '175 sqyrd', '2982 sqft', '758 sqft', '103 sqyrd', '1110 sqft',
       '4734 sqft', '975 sqft', '1707 sqft', '78 sqyrd', '78 sqm',
       '620 sqft', '1735 sqft', '2623 sqft', '180 sqyrd', '943 sqft',
       '650 sqft', '1200 sqft', '2640 sqft', '672 sqft', '1435 sqft',
       '105 sqyrd', '2750 sqft', '110 sqyrd', '1400 sqft', '498 sqft',
       '665 sqft', '1170 sqft', '389 sqft', '660 sqft', '960 sqft',
       '95 sqyrd', '743 sqft', '805 sqft', '3100 sqft', '750 sqft',
       '775 sqft', '874 sqft', '600 sqft', '861 sqft', '700 sqft',
       '1100 sqft', '788 sqft', '430 sqft', '934 sqft', '2041 sqft',
       '1181 sqft', '400 sqft', '976 sqft', '135 sqft', '117 sqyrd',
       '432 sqft', '877 sqft', '730 sqft', '480 sqft', '727 sqft',
       '1280 sqft', '527 sqft', '745 sqft', '804 sqft', '451 sqft',
       '1267 sqft', '810 sqft', '185 sqyrd', '1266 sqft', '350 sqft',
       '1800 sqft', '486 sqft', '520 sqft', '440 sqft', '850 sqft',
       '1056 sqft', '792 sqft', '2300 sqft', '870 sqft', '936 sqft',
       '312 sqyrd', '2000 sqft', '510 sqft', '640 sqft', '740 sqft',
       '1162 sqft', '783 sqft', '1039 sqft', '2600 sqft', '385 sqft',
       '120 sqyrd', '845 sqft', '85 sqyrd', '756 sqft', '631 sqft',
       '1680 sqft', '530 sqft', '879 sqft', '906 sqft', '585 sqft',
       '945 sqft', '1900 sqft', '1345 sqft', '2100 sqft', '1490 sqft',
       '390 sqft', '721 sqft', '1225 sqft', '2121 sqft', '119 sqft',
       '1500 sqft', '2070 sqft', '333 sqft', '100 sqyrd', '1130 sqft',
       '3000 sqft', '895 sqft', '930 sqft', '1463 sqft', '69 sqyrd',
       '551 sqft', '825 sqft', '3025 sqft', '379 sqft', '1306 sqft',
       '1166 sqft', '812 sqft', '830 sqft', '978 sqft', '2367 sqft',
       '795 sqft', '915 sqft', '1180 sqft', '1300 sqft', '438 sqft',
       '1480 sqft', '1123 sqft', '1150 sqft', '1375 sqft', '540 sqft',
       '1946 sqft', '779 sqft', '1075 sqft', '4458 sqft', '1068 sqft',
       '1090 sqft', '80 sqyrd', '763 sqft', '1750 sqft', '121 sqyrd',
       '54 sqft', '1409 sqft', '1340 sqft', '82 sqft', '1135 sqft',
       '2800 sqft', '1620 sqft', '5000 sqft', '565 sqft', '1960 sqft',
       '990 sqft', '1575 sqft', '1007 sqft', '1080 sqft', '490 sqft',
       '633 sqft', '2704 sqft', '771 sqft', '450 sqft', '720 sqft',
       '1296 sqft', '151 sqyrd', '1710 sqft', '857 sqft', '2614 sqft',
       '3075 sqft', '790 sqft', '75 sqyrd', '586 sqft', '1356 sqft',
       '1122 sqft', '1073 sqft', '1777 sqft', '1156 sqft', '575 sqft',
       '878 sqft', '421 sqft', '885 sqft', '715 sqft', '392 sqft',
       '1525 sqft', '1154 sqft', '891 sqft', '1119 sqft', '2205 sqft',
       '1968 sqft', '615 sqft', '2200 sqft', '1187 sqft', '475 sqft',
       '1484 sqft', '2122 sqft', '1120 sqft', '330 sqft', '2085 sqft',
       '3311 sqft', '65 sqm', '1205 sqft', '1839 sqft', '709 sqft',
       '1002 sqft', '713 sqft', '1726 sqft', '865 sqft', '1107 sqft',
       '864 sqft', '925 sqft', '734 sqft', '509 sqft', '848 sqft',
       '654 sqft', '673 sqft', '1600 sqft', '907 sqft', '115 sqyrd',
       '2500 sqft', '671 sqft', '690 sqft', '1720 sqft', '735 sqft',
       '982 sqft', '495 sqft', '1382 sqft', '410 sqft', '1290 sqft',
       '705 sqft', '3150 sqft', '1700 sqft', '956 sqft', '2099 sqft',
       '663 sqft', '434 sqft', '884 sqft', '1040 sqft', '2720 sqft',
       '765 sqft', '1610 sqft', '2310 sqft', '738 sqft', '576 sqft',
       '502 sqft', '1450 sqft', '1989 sqft', '760 sqft', '370 sqft',
       '3580 sqft', '1076 sqft', '607 sqft', '970 sqft', '863 sqft',
       '369 sqft', '2859 sqft', '1220 sqft', '751 sqft', '625 sqft',
       '109 sqyrd', '950 sqft', '2172 sqft', '712 sqft', '955 sqft',
       '113 sqyrd', '693 sqft', '2532 sqft', '460 sqft', '3700 sqft',
       '290 sqyrd', '3300 sqft', '923 sqft', '922 sqft', '3120 sqft',
       '1041 sqft', '1240 sqft', '500 sqft', '1215 sqft', '1275 sqft',
       '1177 sqft', '1990 sqft', '2106 sqft', '1420 sqft', '1281 sqft',
       '894 sqft', '1513 sqft', '797 sqft', '294 sqft', '859 sqft',
       '847 sqft', '811 sqft', '272 sqft', '820 sqft', '423 sqft',
       '3800 sqft', '610 sqft', '1980 sqft', '550 sqft', '1153 sqft',
       '992 sqft', '1053 sqft', '769 sqft', '1587 sqft', '655 sqft',
       '3130 sqft', '1108 sqft', '2700 sqft', '1330 sqft', '4000 sqft',
       '888 sqft', '680 sqft', '1640 sqft', '2154 sqft', '2161 sqft',
       '1518 sqft', '887 sqft', '334 sqft', '2400 sqft', '1580 sqft',
       '1027 sqft', '839 sqft', '1242 sqft', '921 sqft', '616 sqft',
       '165 sqyrd', '741 sqft', '957 sqft', '702 sqft', '441 sqft',
       '780 sqft', '1890 sqft', '1516 sqft', '636 sqft', '150 sqyrd',
       '2010 sqft', '1729 sqft', '100 sqft', '1503 sqft', '1262 sqft',
       '767 sqft', '1785 sqft', '220 sqft', '770 sqft', '1320 sqft',
       '455 sqft', '80 sqft', '1188 sqft', '250 sqft', '5200 sqft',
       '77 sqyrd', '980 sqft', '2790 sqft', '856 sqft', '1333 sqft',
       '940 sqft', '425 sqft', '3225 sqft', '1010 sqft', '1775 sqft',
       '1087 sqft', '145 sqft', '1740 sqft', '2485 sqft', '948 sqft',
       '929 sqft', '1325 sqft', '1140 sqft', '1975 sqft', '1116 sqft',
       '1190 sqft', '1363 sqft', '1118 sqft', '679 sqft', '358 sqft',
       '2049 sqft', '4112 sqft', '935 sqft', '51 sqft', '195 sqyrd',
       '685 sqft', '40 sqm', '817 sqft', '603 sqft', '1008 sqft',
       '235 sqyrd', '1811 sqft', '682 sqft', '352 sqft', '809 sqft',
       '446 sqft', '609 sqft', '630 sqft', '225 sqyrd', '623 sqft',
       '8000 sqft', '993 sqft', '1152 sqft', '298 sqft', '1202 sqft',
       '719 sqft', '827 sqft', '3045 sqft', '681 sqft', '952 sqft',
       '1095 sqft', '130 sqyrd', '1410 sqft', '420 sqft', '386 sqft',
       '1048 sqft', '88 sqyrd', '1052 sqft', '2045 sqft', '437 sqft',
       '140 sqyrd', '378 sqft', '1862 sqft', '525 sqft', '890 sqft',
       '593 sqft', '2705 sqft', '2732 sqft', '614 sqft', '2959 sqft',
       '670 sqft', '725 sqft', '472 sqft', '280 sqft', '1367 sqft',
       '688 sqft', '445 sqft', '1426 sqft', '2973 sqft', '2320 sqft',
       '6363 sqm', '1165 sqft', '701 sqft', '624 sqft', '966 sqft',
       '182 sqft', '90 sqyrd', '4400 sqft', '1032 sqft', '686 sqft',
       '611 sqft', '1406 sqft', '675 sqft', '590 sqft', '1962 sqft',
       '2552 sqft', '710 sqft', '1011 sqft', '664 sqft', '1850 sqft',
       '920 sqft', '559 sqft', '2206 sqft', '1714 sqft', '1282 sqft',
       '711 sqft', '375 sqft', '1370 sqft', '92 sqyrd', '1060 sqft',
       '604 sqft', '991 sqft', '826 sqft', '1092 sqft', '882 sqft',
       '125 sqyrd', '1557 sqft', '1260 sqft', '1292 sqft', '4200 sqft',
       '1780 sqft', '752 sqft', '3200 sqft', '172 sqyrd', '910 sqft',
       '2939 sqft', '844 sqft', '1310 sqft', '414 sqft', '562 sqft',
       '1820 sqft', '380 sqft', '777 sqft', '824 sqft', '1286 sqft',
       '643 sqft', '466 sqft', '561 sqft', '818 sqft', '453 sqft',
       '5300 sqft', '1654 sqft', '1141 sqft', '122 sqm', '3835 sqft',
       '1111 sqft', '2796 sqft', '1226 sqft', '1265 sqft', '819 sqft',
       '1630 sqft', '668 sqft', '560 sqft', '802 sqft', '443 sqft',
       '416 sqft', '815 sqft', '1159 sqft', '1168 sqft', '55 sqm',
       '1560 sqft', '1025 sqft', '801 sqft', '1026 sqft', '1615 sqft',
       '1241 sqft', '449 sqft', '1088 sqft', '858 sqft', '840 sqft',
       '2150 sqft', '1395 sqft', '1863 sqft', '1184 sqft', '2050 sqft',
       '535 sqft', '1131 sqft', '468 sqft', '155 sqyrd', '1537 sqft',
       '323 sqft', '828 sqft', '315 sqft', '753 sqft', '2900 sqft',
       '60 sqyrd', '404 sqft'], dtype=object)

In [14]:
print(test_df['location'].value_counts())
print(train_df['Society'].value_counts())

location
ahmedabad      3237
bangalore      2475
thane           236
mumbai          226
nagpur           85
navi-mumbai      84
Name: count, dtype: int64
Society
Nebula Tower                  743
Swati Parkside                263
Cloud 9                       257
Pooja Apartment               247
Adani Shantigram Waterlily    245
                             ...
Prakriti Towers                 1
Ritu Dreams                     1
Suryam Pride                    1
Pushkar Hill                    1
New Akash Ganga                 1
Name: count, Length: 1626, dtype: int64

In [15]:
def remove_USD(df):
    df['Price_USD']=df['Price_USD'].str.replace('USD', '', regex=False).str.strip().astype(float)
    return df
train = remove_USD(train_df)
test = remove_USD(test_df)

In [16]:
def drop_column(df):
    df.drop(columns=['Dimensions', 'Plot Area'], inplace=True)
    return df
train = drop_column(train)
test = drop_column(test)

In [17]:
test_df.head().T

,0,1,2,3,4
Title,3 BHK Ready to Occupy Flat for sale in Bhartiy...,3 BHK Ready to Occupy Flat for sale in DS Max ...,2 BHK Ready to Occupy Flat for sale in Vijay E...,2 BHK Ready to Occupy Flat for sale in Charany...,2 BHK Ready to Occupy Flat for sale Kalyan East
Description,"Thanisandra Main Road, Bangalore has an appeal...",This ready to move-in 3 BHK flat is available ...,2 BHK flat available for sale in Thane in the ...,Have a look at this immaculate 2 BHK flat for ...,"Kalyan East, Thane has an appealing 2 BHK flat..."
location,bangalore,bangalore,thane,bangalore,thane
Carpet Area,1415 sqft,NaN,800 sqft,NaN,NaN
Status,Ready to Move,Ready to Move,Ready to Move,Ready to Move,Ready to Move
Floor,32 out of 32,5 out of 5,5 out of 14,1 out of 3,3 out of 4
Transaction,Resale,Resale,Resale,Resale,Resale
Furnishing,Semi-Furnished,Semi-Furnished,Semi-Furnished,Semi-Furnished,Semi-Furnished
facing,East,NaN,East,NaN,NaN
overlooking,NaN,NaN,Garden/Park,NaN,NaN
Society,NaN,NaN,Vijay Enclave,NaN,NaN
Bathroom,3,4,2,2,4
Balcony,3,NaN,2,NaN,NaN
Car Parking,NaN,NaN,NaN,NaN,NaN
Ownership,NaN,NaN,Co-operative Society,NaN,NaN
Super Area,NaN,3350 sqft,NaN,1100 sqft,1100 sqft
Price_USD,157.0,46.0,NaN,87.0,48.0

In [18]:
def clean_bath_balcony(df):
    df['Bathroom'] = df['Bathroom'].str.replace("> 10", '10').astype(float)
    df['Balcony'] = df['Balcony'].str.replace("> 10", '10').astype(float)
    return df
train = clean_bath_balcony(train)
test = clean_bath_balcony(test)

In [19]:
def car_clean(df):
    df['Car Parking'] = df['Car Parking'].str.extract('(\d+)', expand=False).astype(float)
    return df
train = car_clean(train)
test = car_clean(test)

In [20]:
test_df.head().T

,0,1,2,3,4
Title,3 BHK Ready to Occupy Flat for sale in Bhartiy...,3 BHK Ready to Occupy Flat for sale in DS Max ...,2 BHK Ready to Occupy Flat for sale in Vijay E...,2 BHK Ready to Occupy Flat for sale in Charany...,2 BHK Ready to Occupy Flat for sale Kalyan East
Description,"Thanisandra Main Road, Bangalore has an appeal...",This ready to move-in 3 BHK flat is available ...,2 BHK flat available for sale in Thane in the ...,Have a look at this immaculate 2 BHK flat for ...,"Kalyan East, Thane has an appealing 2 BHK flat..."
location,bangalore,bangalore,thane,bangalore,thane
Carpet Area,1415 sqft,NaN,800 sqft,NaN,NaN
Status,Ready to Move,Ready to Move,Ready to Move,Ready to Move,Ready to Move
Floor,32 out of 32,5 out of 5,5 out of 14,1 out of 3,3 out of 4
Transaction,Resale,Resale,Resale,Resale,Resale
Furnishing,Semi-Furnished,Semi-Furnished,Semi-Furnished,Semi-Furnished,Semi-Furnished
facing,East,NaN,East,NaN,NaN
overlooking,NaN,NaN,Garden/Park,NaN,NaN
Society,NaN,NaN,Vijay Enclave,NaN,NaN
Bathroom,3.0,4.0,2.0,2.0,4.0
Balcony,3.0,NaN,2.0,NaN,NaN
Car Parking,NaN,NaN,NaN,NaN,NaN
Ownership,NaN,NaN,Co-operative Society,NaN,NaN
Super Area,NaN,3350 sqft,NaN,1100 sqft,1100 sqft
Price_USD,157.0,46.0,NaN,87.0,48.0

In [21]:
def extract_totalFloor(df):
    df['Total_Floor'] = df['Floor'].str.extract(r'(\d+)$').astype(float)
    return df
train = extract_totalFloor(train)
test = extract_totalFloor(test)

In [22]:
def extract_mainFloor(df):
    df['Floor_Number'] = df['Floor'].str.extract(r'^(.+?)\s+out of').squeeze().str.replace('Upper Basement', '-1', regex=False).str.replace('Lower Basement', '-2', regex=False).str.replace('Ground', '0', regex=False).astype(float)
    return df
train = extract_mainFloor(train)
test = extract_mainFloor(test)

In [23]:

print(type(train))
print(train.shape)

<class 'pandas.core.frame.DataFrame'>
(19029, 20)

In [24]:
train_df.head().T

,0,1,2,3,4
Title,3 BHK Ready to Occupy Flat for sale in Runwal ...,2 BHK Ready to Occupy Flat for sale in Shilale...,2 BHK Ready to Occupy Flat for sale Koramangala,4 BHK Ready to Occupy Flat for sale in Hiranan...,3 BHK Ready to Occupy Flat for sale Jagatpur
Description,Carefully laid out in the prime location of Gh...,Up for immediate sale is a 2 BHK apartment in ...,This magnificent 2 BHK Flat is available for s...,Have a look at this immaculate 4 BHK flat for ...,Have a look at this immaculate 3 BHK flat for ...
location,mumbai,ahmedabad,bangalore,thane,ahmedabad
Carpet Area,806 sqft,900 sqft,1000 sqft,1520 sqft,NaN
Status,Ready to Move,Ready to Move,Ready to Move,Ready to Move,Ready to Move
Floor,Upper Basement out of 15,1 out of 4,Ground out of 7,14 out of 27,3 out of 9
Transaction,Resale,Resale,New Property,Resale,Resale
Furnishing,Semi-Furnished,Unfurnished,Unfurnished,Unfurnished,Unfurnished
facing,East,NaN,West,East,NaN
overlooking,Main Road,Main Road,Garden/Park,Garden/Park,NaN
Society,Runwal Orchard Residency,Shilalekh Apartments,NaN,Hiranandani Meadows,NaN
Bathroom,2.0,2.0,2.0,4.0,3.0
Balcony,3.0,2.0,1.0,1.0,NaN
Car Parking,1.0,NaN,1.0,2.0,NaN
Ownership,Freehold,Freehold,Freehold,Freehold,NaN
Super Area,NaN,NaN,NaN,NaN,1773 sqft
Price_USD,199.0,70.0,127.0,144.0,50.0
Amount_USD,271084.0,63012.0,186747.0,289157.0,90361.0
Total_Floor,15.0,4.0,7.0,27.0,9.0
Floor_Number,-1.0,1.0,0.0,14.0,3.0

In [25]:

train.drop(columns=['Floor'], inplace=True)
test.drop(columns=['Floor'], inplace=True)

In [26]:
def clean_area(df, col):
    extracted = df[col].str.extract(r'([\d.]+)\s*(sqft|sqyrd|sqm)')
    numbers = extracted[0].astype(float)
    units = extracted[1]

    conversion = {'sqft': 1, 'sqyrd': 9, 'sqm':10.764}

    multiplier = units.map(conversion)

    df[col] = numbers * multiplier

    return df


train = clean_area(train, 'Carpet Area')
train = clean_area(train, 'Super Area')
test = clean_area(test, 'Carpet Area')
test = clean_area(test, 'Super Area')

In [27]:
train_df.head().T

,0,1,2,3,4
Title,3 BHK Ready to Occupy Flat for sale in Runwal ...,2 BHK Ready to Occupy Flat for sale in Shilale...,2 BHK Ready to Occupy Flat for sale Koramangala,4 BHK Ready to Occupy Flat for sale in Hiranan...,3 BHK Ready to Occupy Flat for sale Jagatpur
Description,Carefully laid out in the prime location of Gh...,Up for immediate sale is a 2 BHK apartment in ...,This magnificent 2 BHK Flat is available for s...,Have a look at this immaculate 4 BHK flat for ...,Have a look at this immaculate 3 BHK flat for ...
location,mumbai,ahmedabad,bangalore,thane,ahmedabad
Carpet Area,806.0,900.0,1000.0,1520.0,NaN
Status,Ready to Move,Ready to Move,Ready to Move,Ready to Move,Ready to Move
Transaction,Resale,Resale,New Property,Resale,Resale
Furnishing,Semi-Furnished,Unfurnished,Unfurnished,Unfurnished,Unfurnished
facing,East,NaN,West,East,NaN
overlooking,Main Road,Main Road,Garden/Park,Garden/Park,NaN
Society,Runwal Orchard Residency,Shilalekh Apartments,NaN,Hiranandani Meadows,NaN
Bathroom,2.0,2.0,2.0,4.0,3.0
Balcony,3.0,2.0,1.0,1.0,NaN
Car Parking,1.0,NaN,1.0,2.0,NaN
Ownership,Freehold,Freehold,Freehold,Freehold,NaN
Super Area,NaN,NaN,NaN,NaN,1773.0
Price_USD,199.0,70.0,127.0,144.0,50.0
Amount_USD,271084.0,63012.0,186747.0,289157.0,90361.0
Total_Floor,15.0,4.0,7.0,27.0,9.0
Floor_Number,-1.0,1.0,0.0,14.0,3.0

In [28]:
print(train.isnull().sum() / len(train) * 100)

Title            0.000000
Description      2.270219
location         0.000000
Carpet Area     54.190972
Status           0.147144
Transaction      0.047296
Furnishing       2.201902
facing          47.995165
overlooking     52.314888
Society         65.205739
Bathroom         0.168164
Balcony         37.574229
Car Parking     62.262862
Ownership       44.426927
Super Area      46.875821
Price_USD        4.908298
Amount_USD       0.000000
Total_Floor      3.710127
Floor_Number     3.720637
dtype: float64

### REPLACE NAN WITH MODE FOR CATEGORICAL, MEDIAN FOR NUMERIC

In [29]:
cols_to_drop = ['Society', 'Car Parking', 'Carpet Area', 
                'overlooking', 'facing', 'Ownership', 'Description']

def drop_cols(df):
    return df.drop(columns=cols_to_drop)

train = drop_cols(train)
test = drop_cols(test)

In [30]:
train_df.head().T

,0,1,2,3,4
Title,3 BHK Ready to Occupy Flat for sale in Runwal ...,2 BHK Ready to Occupy Flat for sale in Shilale...,2 BHK Ready to Occupy Flat for sale Koramangala,4 BHK Ready to Occupy Flat for sale in Hiranan...,3 BHK Ready to Occupy Flat for sale Jagatpur
Description,Carefully laid out in the prime location of Gh...,Up for immediate sale is a 2 BHK apartment in ...,This magnificent 2 BHK Flat is available for s...,Have a look at this immaculate 4 BHK flat for ...,Have a look at this immaculate 3 BHK flat for ...
location,mumbai,ahmedabad,bangalore,thane,ahmedabad
Carpet Area,806.0,900.0,1000.0,1520.0,NaN
Status,Ready to Move,Ready to Move,Ready to Move,Ready to Move,Ready to Move
Transaction,Resale,Resale,New Property,Resale,Resale
Furnishing,Semi-Furnished,Unfurnished,Unfurnished,Unfurnished,Unfurnished
facing,East,NaN,West,East,NaN
overlooking,Main Road,Main Road,Garden/Park,Garden/Park,NaN
Society,Runwal Orchard Residency,Shilalekh Apartments,NaN,Hiranandani Meadows,NaN
Bathroom,2.0,2.0,2.0,4.0,3.0
Balcony,3.0,2.0,1.0,1.0,NaN
Car Parking,1.0,NaN,1.0,2.0,NaN
Ownership,Freehold,Freehold,Freehold,Freehold,NaN
Super Area,NaN,NaN,NaN,NaN,1773.0
Price_USD,199.0,70.0,127.0,144.0,50.0
Amount_USD,271084.0,63012.0,186747.0,289157.0,90361.0
Total_Floor,15.0,4.0,7.0,27.0,9.0
Floor_Number,-1.0,1.0,0.0,14.0,3.0

In [31]:
train_df['Total_Floor'].dtype

dtype('float64')

######❌ Never calculate median from test and use it — that's data leakage
✅ Always learn statistics from train, apply to both

In [32]:

numeric_cols =['Super Area', 'Balcony',  'Price_USD', 'Total_Floor', 'Floor_Number', 'Bathroom']

catrgorical_cols = ['Furnishing', 'Status', 'Transaction']

numeric_medians = train[numeric_cols].median()

categorical_modes = train[catrgorical_cols].mode().iloc[0]

def impute(df):
    df[numeric_cols] = df[numeric_cols].fillna(numeric_medians)
    df[catrgorical_cols] = df[catrgorical_cols].fillna(categorical_modes)
    return df

train = impute(train)
test = impute(test)

In [33]:
print(train.isnull().sum())
print(train.dtypes)
print(train.shape)

Title           0
location        0
Status          0
Transaction     0
Furnishing      0
Bathroom        0
Balcony         0
Super Area      0
Price_USD       0
Amount_USD      0
Total_Floor     0
Floor_Number    0
dtype: int64
Title            object
location         object
Status           object
Transaction      object
Furnishing       object
Bathroom        float64
Balcony         float64
Super Area      float64
Price_USD       float64
Amount_USD      float64
Total_Floor     float64
Floor_Number    float64
dtype: object
(19029, 12)